#!/usr/bin/env bash
# Configures Cargo to build Rust examples against the installed nxusKit SDK.
#
# Generates .cargo/config.toml with a Cargo `paths` override that redirects
# the stub crate at sdk/nxuskit-rust/ to the real SDK installed at
# ~/.nxuskit/sdk/current/rust/.
#
# Without this setup, Rust builds fail with:
#   "nxuskit SDK not configured. Run: ./scripts/setup-sdk-symlink.sh"
#
# Usage:
#   ./scripts/setup-sdk-symlink.sh
#
# Prerequisites:
#   nxusKit SDK must be installed (nxuskit install)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SDK_SOURCE="$HOME/.nxuskit/sdk/current/rust"
CARGO_CONFIG="$REPO_ROOT/.cargo/config.toml"

# --- Verify SDK is installed ---

if [ ! -d "$SDK_SOURCE" ]; then
    echo "Error: SDK not found at $SDK_SOURCE"
    echo "Install the nxusKit SDK first: nxuskit install"
    exit 1
fi

if [ ! -f "$SDK_SOURCE/Cargo.toml" ]; then
    echo "Error: $SDK_SOURCE/Cargo.toml not found"
    echo "The SDK installation appears incomplete. Reinstall: nxuskit install"
    exit 1
fi

# --- Resolve absolute path ---

SDK_ABSOLUTE="$(cd "$SDK_SOURCE" && pwd -P)"

# --- Generate .cargo/config.toml ---

mkdir -p "$REPO_ROOT/.cargo"
cat > "$CARGO_CONFIG" <<EOF
# Auto-generated by scripts/setup-sdk-symlink.sh — do not commit.
# Overrides the nxuskit stub crate with the locally installed SDK.
paths = ["$SDK_ABSOLUTE"]
EOF

echo "Generated .cargo/config.toml"
echo "  nxuskit -> $SDK_ABSOLUTE"
echo ""
echo "Rust examples will now build against the installed SDK."
